### ISSUE TITLE
java-sdk As User return Empty BoxFile.Info

### ISSUE THREAD

**Issue by ccao-msi** [box/box-java-sdk#682] opened 2019-02-15 22:08 UTC
- [X] I have checked that the Java SDK docs and https://developer.box.com/reference doesn't solve my issue

### Description of the Issue

We're using As-User function to access BoxFile and BoxFile.info object.  
It returns an empty BoxFile.info object when using the Java API to get the BoxFile as a user(see AsUserSdkCallTest.java).
However, when making REST API calls,  we are able to get a file from box and retrieve it's information when we specify the As-User header (see AsUserRestCallTest.java).  

### Versions Used
Java SDK: 2.22.0 and 2.27.0  
Java: jdk 10.0.1

### Steps to Reproduce
run tests on AsUserRestCallTest.java and AsUserSdkCallTest.java
printout are shown in AsUserRestCallTest.log and AsUserSdkCallTest.log

### Error Message, Including Stack Trace
no error message. just empty BoxFile.Info object

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[AsUserRestCallTest.java.txt](https://github.com/box/box-java-sdk/files/2871037/AsUserRestCallTest.java.txt)
[AsUserSdkCallTest.java.txt](https://github.com/box/box-java-sdk/files/2871038/AsUserSdkCallTest.java.txt)
[JWTConnectBaseIT.java.txt](https://github.com/box/box-java-sdk/files/2871039/JWTConnectBaseIT.java.txt)
[AsUserRestCallTest.log](https://github.com/box/box-java-sdk/files/2871042/AsUserRestCallTest.log)
[AsUserSdkCallTest.log](https://github.com/box/box-java-sdk/files/2871043/AsUserSdkCallTest.log)

**Comment by carycheng** [comment] 2019-02-19 20:58
Hey @ccao-msi,

Thank you for writing in and providing your test cases. We really appreciate it! We will run them and provide you with an answer shortly. 

If there is anything else in the meantime that you are having issues with please don't hesitate to let us know.

**Comment by carycheng** [comment] 2019-02-21 01:52
Hey @ccao-msi, 

Unfortunately we were unable to reproduce this error. We used the below snippet and were able to retrieve the file object.

```java
        BoxAPIConnection api = new BoxAPIConnection("ACCESS_TOKEN");
        api.asUser("USER_ID");
        BoxFile file = new BoxFile(api, "FILE_ID");
        BoxFile.Info fileInfo = file.getInfo();
```

An alternative, if you could send us your API Key to `sdks@box.com`, we will do our best to look up your calls internally to try and find where this issue might be occurring.

Thank you for your patience!

**Comment by ccao-msi** [comment] 2019-02-21 13:02
Hi,
   We used JWT instead of  access_token.  We can get FileInfo but it's empty.   I'll email you our API key.  Thanks.

**Comment by ccao-msi** [comment] 2019-02-21 14:37
The email address sdks@box.com is not accepting my email.  Please let me know if there is another email that I could use.  
Also, this issue was logged with your box customer support  (Case #1846365) and we already emailed them our API keys.

**Comment by carycheng** [comment] 2019-02-22 08:35
Hey @ccao-msi, 

We were able to track down your case from your ticket number, thank you! We looked through our logs and were unsuccessful in finding an erroneous response from the API that might have something to do with your issue.

We are still very much committed to solving this issue but we require a bit of additional leg work on your end. Apologies!

If possible, could you run the below snippet and let us know what the logs come back with? The reason why we are doing this breaks down threefold, we would like to see and compare:
1. The outbound request to make sure all the headers and url line up.
2. The JSON response that comes back before any object transforming has occurred.
3. The formed BoxFile.Info object from a REST call.
4. The formed BoxFile.Info object from an SDK call. 

```java
    @Test
    @Category(UnitTest.class)
    public void testAsUser() {
        BoxAPIConnection api = new BoxAPIConnection("ACCESS_TOKEN");
        String BoxFileID = "FILE_ID";
        String BoxUserID = "USER_ID";

        // Request interceptor to see what the outbound request looks like.
        api.setRequestInterceptor(new RequestInterceptor() {
            @Override
            public BoxAPIResponse onRequest(BoxAPIRequest request) {
                LOGGER.debug("@@---Request Object");

                for (BoxAPIRequest.RequestHeader r : request.getHeaders()) {
                    LOGGER.debug(r.getKey() + " : " + r.getValue());
                }
                return null;
            }
        });

        URLTemplate FILE_URL_TEMPLATE = new URLTemplate("files/%s");
        URL url = FILE_URL_TEMPLATE.build(api.getBaseURL(), BoxFileID);
        BoxAPIRequest request = new BoxAPIRequest(api, url, "GET");
        request.addHeader("As-User", BoxUserID);

        BoxJSONResponse response = (BoxJSONResponse) request.send();

        LOGGER.debug("@@---JSON Response");
        LOGGER.debug("Created By Name: " + response.getJsonObject().get("created_by").asObject().get("name").toString());
        LOGGER.debug("Created By Login: " + response.getJsonObject().get("created_by").asObject().get("login").toString());
        LOGGER.debug("Created By ID: " + response.getJsonObject().get("created_by").asObject().get("id").toString());

        BoxFile file = new BoxFile(api, response.getJsonObject().get("id").toString());
        BoxFile.Info info = file.new Info(response.getJsonObject());
        
        LOGGER.debug("@@---Rest Call");
        LOGGER.debug("Created By Name: " + info.getCreatedBy().getName());
        LOGGER.debug("Created By Login: " + info.getCreatedBy().getLogin());
        LOGGER.debug("Created By ID: " + info.getCreatedBy().getID());

        api.asUser(BoxUserID);
        BoxFile newFile = new BoxFile(api, BoxFileID);
        BoxFile.Info newFileInfo = newFile.getInfo();

        LOGGER.debug("@@---SDK Call");
        LOGGER.debug("Created At By Name: " + newFileInfo.getCreatedBy().getName());
        LOGGER.debug("Created At By Login: " + newFileInfo.getCreatedBy().getLogin());
        LOGGER.debug("Created At By ID: " + newFileInfo.getCreatedBy().getID());
    }
```

And if possible, if you could send us a network trace of any kind that would be very helpful as well.

One thing to note is that although this may not be directly related to your issue, the version number for a BoxFile does not come back automatically. That is a field you have to explicitly request.

Thank you so much for you patience and we look forward to your response!

**Comment by ccao-msi** [comment] 2019-02-22 14:54
Hi,
  there is one error when compile the above method:
     request.getHeaders() has protected access in BoxAPIRequest.
  So, I'm not able to print the headers. Please advise.  Thanks.

**Comment by carycheng** [comment] 2019-02-22 21:55
Hey @ccao-msi, 

I would just remove that line for now, we mostly want to see the difference between:

1. The JSON response that is returned by the API.
2. What the response looks like after converted to BoxFile.Info object from a REST call.
3. What the response looks like after converted to BoxFile.Info object from an SDK call.

Another couple of items that would helps us greatly if answered were:

1. Are you using a proxy of any sort?
2. Do you have a network trace of the request outbound?

Thank you for biding with us!

**Comment by ccao-msi** [comment] 2019-02-25 01:42
Hi,
  We finally get SDK call for as-user to work.  It matches the REST call.  Thank you for your help and you can close this issue now.

**Comment by carycheng** [comment] 2019-02-25 18:44
Hey @ccao-msi, 

Really happy it's working! Can you please let us know what steps you took to fix your issue? 

We are very curious and would love to find out the resolution for bookkeeping.

Thank you!

**Closed** 2019-03-10 07:59 UTC
