### ISSUE TITLE
Chunked Upload digest_mismatch Error

### ISSUE THREAD

**Issue by qrdean** [box/box-java-sdk#701] opened 2019-05-08 19:20 UTC
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm having an issue when I attempt to commit my session during a chunked upload session using the box-java-sdk with some of the chunked upload methods.

I've created a chunked method that follows this doc:
https://github.com/box/box-java-sdk/blob/master/doc/files.md#upload-a-large-file-in-chunks

The function works until I attempt to commit my session. I get an error 400 digest_mismatch - File digest was incorrect. Actual: I9YWC4PWLXwDLtBnskju3LXGIOw= Expected: 0z1JQ/aCu1KF9AwwYfYdoXuOk0M=

``` java
private BoxFile.Info chunkUploading(BoxAPIConnection api, InputStream fileData, String fileName, long fileLength, String boxId, boolean newVersion) throws Exception {
		log.traceEntry("Entered chunking upload. api: {}, File: {}, box Id: {}, newVersion: {}", api.toString(), fileName, boxId, newVersion);
		long fileSize = fileLength;
		BoxFileUploadSession.Info sessionInfo;
		
		if (!newVersion) {
			BoxFolder rootFolder = new BoxFolder(api, boxId);
			sessionInfo = rootFolder.createUploadSession(fileName, fileSize);
		} else {
			BoxFile file = new BoxFile(api, boxId);
			sessionInfo = file.createUploadSession(fileSize);
		}
		
		// Get the session resource from the session info
		BoxFileUploadSession session = sessionInfo.getResource();
		
		// Create the Message Digest for the whole file
		MessageDigest digest = null;
		try {
			digest = MessageDigest.getInstance("SHA1");
		} catch (NoSuchAlgorithmException ae) {
			throw new BoxAPIException("Digest algorithm not found", ae);
		}
	
		// Reading large file
//		FileInputStream fis = new FileInputStream(fileName);
		// Create the digest input stream to calculate the digest for the whole file.
		DigestInputStream dis = new DigestInputStream(fileData, digest);
		
		List<BoxFileUploadSessionPart> parts = new ArrayList<BoxFileUploadSessionPart>();
		
		// Get the part size. Each uploaded part should match the part size returned as part of the upload session.
		// The last part of the file can be less than part size if the remaining bytes of the last part is less than
		// the given part size
		long partSize = sessionInfo.getPartSize();
		log.debug("partsize1: {}", partSize);
		// Start byte of the part;
		long offset = 0;
		// Overall of bytes processed so far
		long processed = 0;
		while (processed < fileSize) {
			long diff = fileSize - processed;
			// The size last part of the file can be less than the part size.
			if (diff < partSize) {
				partSize = diff;
			}
			
			// Upload a part. It can be uploaded async
			BoxFileUploadSessionPart part = session.uploadPart(dis, offset, (int)partSize, fileSize);

			parts.add(part);
			

			processed += partSize;
			offset += partSize;
		}

		// Create the file hash
		byte[] digestBytes = digest.digest();
		// Base64 encoding of the hash
		String digestStr = Base64.getEncoder().encodeToString(digestBytes);
		log.debug("digestStr: {}", digestStr);
		dis.close();
		
		// Commit the upload session. If there is a failure, abort the commit.
		BoxFile.Info newFileInfo = session.commit(digestStr, parts, null, null, null);
		return newFileInfo;
	}
```

I've also attempted to use the built in uploadLargeFile method and I get the same digest string I9YWC4PWLXwDLtBnskju3LXGIOw= as in my own "custom" method.
``` java
private BoxFile.Info chunkTest(BoxAPIConnection api, InputStream fileData, String fileName, long fileLength, String boxId, boolean newVersion) throws Exception {
		log.traceEntry("testing built in chunking. api: {}, File: {}, size: {}, box Id: {}, newVersion: {}", api.toString(), fileName, fileLength, boxId, newVersion);
		BoxFile.Info fileInfo;
		if (!newVersion) {
			BoxFolder rootFolder = new BoxFolder(api, boxId);
			fileInfo = rootFolder.uploadLargeFile(fileData, fileName, fileLength);
		} else {
			BoxFile file = new BoxFile(api, boxId);
			fileInfo = file.uploadLargeFile(fileData, fileLength);
		}
		return fileInfo;
	}
```

### Versions Used
Java SDK: 2.24.0
Java: 1.8.0_144

### Steps to Reproduce
Attempt to upload a new file with a custom chunked upload or with the uploadLargeFile method.

### Error Message, Including Stack Trace
```
com.box.sdk.BoxAPIResponseException: The API returned an error code [400 | a39a1b4605b9a98f8725095987c97cc0] digest_mismatch - File digest was incorrect. Actual: I9YWC4PWLXwDLtBnskju3LXGIOw= Expected: 0z1JQ/aCu1KF9AwwYfYdoXuOk0M=
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92) ~[box-java-sdk-2.32.0.jar:?]
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32) ~[box-java-sdk-2.32.0.jar:?]
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:579) ~[box-java-sdk-2.32.0.jar:?]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:354) ~[box-java-sdk-2.32.0.jar:?]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:329) ~[box-java-sdk-2.32.0.jar:?]
	at com.box.sdk.BoxFileUploadSession.commit(BoxFileUploadSession.java:352) ~[box-java-sdk-2.32.0.jar:?]
	at com.adj.or.rest.BoxREST.chunkUploading(BoxREST.java:1202) ~[classes/:?]
	at com.adj.or.rest.BoxREST.uploadRequestFile(BoxREST.java:847) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:258) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.4.jar:1.19.4]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.4.jar:1.19.4]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.4.jar:1.19.4]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.12]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.12]
	at com.adj.or.rest.WebFilterREST.doFilter(WebFilterREST.java:68) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.12]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.10.0.jar:2.10.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.12]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:9.0.12]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:9.0.12]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.12]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668) [catalina.jar:9.0.12]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.12]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.12]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-coyote.jar:9.0.12]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-coyote.jar:9.0.12]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770) [tomcat-coyote.jar:9.0.12]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415) [tomcat-coyote.jar:9.0.12]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.12]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.12]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment] 2019-05-09 00:58
Hey @qrdean,

Thank you for writing in, we will look into this and get back to you with more information.

**Comment by carycheng** [comment] 2019-05-14 00:37
Hello @qrdean,

It looks like there is a potential bug in the SDK that could be triggered when there is a mis-match between the actual file size and the file size the user passes in, we will continue looking into this, however, in the meantime something that may fix this issue is: could you double check the file size you are passing into the upload method and ensure that it is indeed the same as the actual file size?

**Comment by qrdean** [comment] 2019-05-14 14:27
Gotcha, that's interesting.

In the current implementation the file size is sent in via the client by passing it via a FormDataParam. I double checked the InputStream's size server side by copying it into a File and reading it. The client side file size passed in and the server side File.length() equal each other. 

The only thing I could think of is the InputStream being modified in between, but I'm don't see any places that happens.

**Comment by qrdean** [comment] 2019-05-16 14:08
@carycheng needed to copy the file to our server first, read the length, then create a FileInputStream from that file. Previously I was attempting to stream the data directly and there was obviously a mismatch between the actual File that was saved to the server and that direct stream of data.

code:
``` java
InputStream fileData from somewhere

String path = tempPath + fileName;
File file = new File(path);
FileUtils.copyInputStreamToFile(fileData, file);
```

after the MessageDigest is created

``` java
FileInputStream fis = new FileInputStream(file);
DigestInputStream dis = new DigestInputStream(fis, digest);
```
Thanks for the heads up on the file size that helped key us into what the problem was with our implementation.

**Comment by carycheng** [comment] 2019-05-22 22:48
Hey @qrdean,

Glad you were able to get it working! We have a fix for this that should be going out with our next release that you can see here #703.

Thanks for bearing with us!

**Comment by carycheng** [comment] 2019-05-23 21:57
Hey @qrdean,

We just released v2.33.0 of the sdk with the patch for the upload issue you have discovered. Please let us know if that resolves your issue!

If you run into any issues or have any questions please reach out to us, thanks!

**Closed** 2019-06-09 02:50 UTC
Labels: bug

**Comment by LeasyZhang** [comment] 2019-06-12 02:26
Hey @carycheng 

I'm having the same issue with qrdean, I'm using box-java-sdk to stream the data from S3 to Box. As qrdean described above, He/She choose to save the file to local and then upload to Box, is there any solution to transfer from a stream to Box?
I'm using box-java-sdk v2.33.0 and this error still exists.

Thanks!

**Comment by carycheng** [comment] 2019-06-12 22:31
Hey @LeasyZhang,

Thank you for reaching out. We will continue looking into this, what can be helpful for us to reproduce and speed this process along is if you could provide us with:

1. A code snippet you are running and getting this error with and
2. Access to a public S3 bucket where we can run this snippet against in order for us to reproduce

Any of the above would be really helpful, thank you!

**Comment by LeasyZhang** [comment] 2019-06-13 01:04
Hey @carycheng ,

Thank you for willing to help, I find a public url refers to a large file(> 20MB), the url is `https://vscode.cdn.azure.cn/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/VSCode-darwin-stable.zip`.
And the code snippet is

`
  //code snippet, url is provided above, accessToken can be generated by Box API console

        URL contentUrl = new URL(url);

        URLConnection connection = contentUrl.openConnection();
        long fileSize = connection.getContentLength();
        BoxFileUploadSession.Info sessionInfo;

        BoxAPIConnection api = new BoxAPIConnection(accessToken);
        BoxFolder rootFolder = BoxFolder.getRootFolder(api);
        rootFolder.getInfo().getResource();

        String fileName = "VSCode.dmg";
        rootFolder.canUpload(fileName, fileSize);

        sessionInfo = rootFolder.createUploadSession(fileName, fileSize);
        BoxFileUploadSession session = sessionInfo.getResource();

        MessageDigest digest = MessageDigest.getInstance("SHA1");
        InputStream inputStream = connection.getInputStream();
        DigestInputStream dis = new DigestInputStream(inputStream, digest);

        List<BoxFileUploadSessionPart> parts = new ArrayList<>();
        int partSize = sessionInfo.getPartSize();
        long offset = 0;
        long processed = 0;

        while (processed < fileSize) {
            long diff = fileSize - processed;

            if (diff < partSize) {
                partSize = (int) diff;
            }


            BoxFileUploadSessionPart part = session.uploadPart(dis, offset, partSize, fileSize);
            parts.add(part);

            processed += partSize;
            offset += partSize;
        }
        byte[] digestBytes = digest.digest();
        String digestStr = Base64.encodeBase64String(digestBytes);
        BoxFile.Info fileInfo = session.commit(digestStr, parts, null, null, null);`

and error message is same as qrdean.

I hope above information would helpful, thank you!

**Comment by carycheng** [comment] 2019-06-17 21:08
Hello @LeasyZhang,

I see that one of the issues is that you are passing in the entire stream into the DigestInputStream() in order to create your instance dis. That may not be the correct input.

However, is there a reason why you are using the manual way of doing a chunked upload? If there are no specific reasons we would recommend you using the automatic chunked uploader which abstracts away a lot of the manual processes you see above. You can find an example of this [here](https://github.com/box/box-java-sdk/blob/master/doc/files.md#upload-a-large-file-in-chunks).

If you would still like to do this manually then we have examples for that as well that you can find [here](https://github.com/box/box-java-sdk/blob/master/doc/files.md#upload-a-large-file-or-file-version-manually).

Please let us know if this is helpful and let us know if any issues may come up in this process, thank you!

**Comment by LeasyZhang** [comment] 2019-07-18 05:07
Hello @carycheng 

Sorry for reply so late.
I use manual upload because I need to controller the upload speed, and avoid trigger Box API rate limit warning.
The code snippet was taking from [here](https://github.com/box/box-java-sdk/blob/master/doc/files.md#upload-a-large-file-or-file-version-manually), the difference is the example upload a local file while I upload a file from a url. and the error still exists.

Thanks for the detailed explanation and I hope the SDK could support upload from a url in the future version.
Thank you.
