### ISSUE TITLE
EventLog.getEnterpriseEvents fails when it is called with timezone containing "+"

### ISSUE THREAD

**Issue by hiroyukitanaka** [box/box-java-sdk#198] opened 2016-01-22 05:38 UTC
com.box.sdk.EventLog.getEnterpriseEvents ends with BoxAPIException when it is called with "+" timezone.

My PC's timezone setting is "(UTC+09:00) Osaka,Sapporo,Tokyo".

I wrote the following code:
```java
BoxAPIConnection api = new BoxAPIConnection("my-developer-token"); 

Calendar cal = Calendar.getInstance();
Date before = cal.getTime();
cal.add(Calendar.DATE, -10);
Date after = cal.getTime();
		
EventLog log = EventLog.getEnterpriseEvents(api, after, before);
```

When I execute the above code, BoxAPIException occurs with the following message.
```
com.box.sdk.BoxAPIException: The API returned an error code: 400
```

I found the following implementation in EventLog.getEnterpriseEvents function.
```java
String afterString = BoxDateFormat.format(after);
String beforeString = BoxDateFormat.format(before);
URL url = ENTERPRISE_EVENT_URL_TEMPLATE.build(api.getBaseURL(), afterString, beforeString);
```

And, I found that `url` has like the following `query` value, when I execute my code on my PC.
```
stream_type=admin_logs&limit=500&created_after=2016-01-12T14:20:18+0900&created_before=2016-01-22T14:20:18+0900
```

I've tried to call Enterprise Events API with the above query, and, I've got 400 response code.
When I tried to URL encode "+" and call the same API, I've got OK response. 
```
stream_type=admin_logs&limit=500&created_after=2016-01-12T14:20:18%2B0900&created_before=2016-01-22T14:20:18%2B0900
```

I think that `afterString` and `beforeString` in EventLog.getEnterpriseEvents function should be URL encoded like:
```java
String afterString = URLEncoder.encode(BoxDateFormat.format(after), "UTF-8");
String beforeString = URLEncoder.encode(BoxDateFormat.format(before), "UTF-8");
```

**Comment by cburnette** [comment] 2016-01-22 16:55
@gcurtis it looks like the appendParam method on QueryStringBuilder class is encoding the string, but the afterString and beforeString params were added using the build method on URLTemplate class.  That method doesn't appear to do any encoding.

**Comment by gcurtis** [comment] 2016-01-22 21:17
Yeah, it looks ike the before and after params should be removed from the template and instead added with the `QueryStringBuilder`.

**Comment by danielandefors** [comment] 2016-01-22 22:28
Maybe duplicate of #131?

**Closed** 2016-06-15 20:51 UTC
Labels: bug
